{$define UNIGUI_VCL}

{$ifndef UNIGUI_VCL}
  library
{$else}
  program
{$endif}
  Controle;

uses
  uniGUIISAPI,
  Forms,
  Controle.Server.Module in 'Controle.Server.Module.pas' {ControleServerModule: TUniGUIServerModule},
  Controle.Consulta.Fornecedor in 'Controle.Consulta.Fornecedor.pas' {ControleConsultaFornecedor: TUniFrame},
  Controle.Consulta.Cliente in 'Controle.Consulta.Cliente.pas' {ControleConsultaCliente: TUniFrame},
  Controle.Main in 'Controle.Main.pas' {ControleMain: TUniForm},
  Controle.Consulta.Modal.Pessoa in 'Controle.Consulta.Modal.Pessoa.pas' {ControleConsultaModalPessoa: TUniForm},
  Controle.Consulta.Modal.Cidade in 'Controle.Consulta.Modal.Cidade.pas' {ControleConsultaModalCidade: TUniForm},
  Controle.Cadastro.Fornecedor in 'Controle.Cadastro.Fornecedor.pas' {ControleCadastroFornecedor: TUniForm},
  Controle.Consulta.Vendedor in 'Controle.Consulta.Vendedor.pas' {ControleConsultaVendedor: TUniFrame},
  Controle.Cadastro.Vendedor in 'Controle.Cadastro.Vendedor.pas' {ControleCadastroVendedor: TUniForm},
  Controle.Consulta.Filial in 'Controle.Consulta.Filial.pas' {ControleConsultaFilial: TUniFrame},
  Controle.Cadastro.Filial in 'Controle.Cadastro.Filial.pas' {ControleCadastroFilial: TUniForm},
  Controle.Consulta.Modelo in 'Controle.Consulta.Modelo.pas' {ControleConsultaModelo: TUniFrame},
  Controle.Cadastro.Modelo in 'Controle.Cadastro.Modelo.pas' {ControleCadastroModelo: TUniForm},
  Controle.Cadastro.Usuario in 'Controle.Cadastro.Usuario.pas' {ControleCadastroUsuario: TUniForm},
  Controle.Modal.Ajuda in 'Controle.Modal.Ajuda.pas' {ControleModalAjuda: TUniForm},
  Controle.Consulta.Menu.Schema in 'Controle.Consulta.Menu.Schema.pas' {ControleConsultaMenuSchema: TUniFrame},
  Controle.Consulta.Schema in 'Controle.Consulta.Schema.pas' {ControleConsultaSchema: TUniFrame},
  Controle.Cadastro.Schema in 'Controle.Cadastro.Schema.pas' {ControleCadastroSchema: TUniForm},
  Controle.Consulta.Banco in 'Controle.Consulta.Banco.pas' {ControleConsultaBanco: TUniFrame},
  Controle.Consulta.ContaBancaria in 'Controle.Consulta.ContaBancaria.pas' {ControleConsultaContaBancaria: TUniFrame},
  Controle.Cadastro.Banco in 'Controle.Cadastro.Banco.pas' {ControleCadastroBanco: TUniForm},
  Controle.Cadastro.ContaBancaria in 'Controle.Cadastro.ContaBancaria.pas' {ControleCadastroContaBancaria: TUniForm},
  Controle.Consulta.CondicoesPagamento in 'Controle.Consulta.CondicoesPagamento.pas' {ControleConsultaCondicoesPagamento: TUniFrame},
  Controle.Cadastro.CondicoesPagamento in 'Controle.Cadastro.CondicoesPagamento.pas' {ControleCadastroCondicoesPagamento: TUniForm},
  Controle.Consulta.TituloReceber in 'Controle.Consulta.TituloReceber.pas' {ControleConsultaTituloReceber: TUniFrame},
  Controle.Cadastro.TituloReceber in 'Controle.Cadastro.TituloReceber.pas' {ControleCadastroTituloReceber: TUniForm},
  Controle.Operacoes.CriarTituloReceber in 'Controle.Operacoes.CriarTituloReceber.pas' {ControleOperacoesCriarTituloReceber: TUniForm},
  Controle.Consulta.Modal.TipoTitulo in 'Controle.Consulta.Modal.TipoTitulo.pas' {ControleConsultaModalTipoTitulo: TUniForm},
  Controle.Consulta.Modal.Banco in 'Controle.Consulta.Modal.Banco.pas' {ControleConsultaModalTituloCategoria: TUniForm},
  Controle.Consulta.Modal.ContaBancaria in 'Controle.Consulta.Modal.ContaBancaria.pas' {ControleConsultaModalContaBancaria: TUniForm},
  Controle.Impressao.Carne in 'Controle.Impressao.Carne.pas' {ControleImpressaoCarne: TUniForm},
  Controle.Mensagem.Erro in 'Controle.Mensagem.Erro.pas' {ControleMensagemErro: TUniForm},
  Controle.Impressao.Documento in 'Controle.Impressao.Documento.pas' {ControleImpressaoDocumento: TUniForm},
  Controle.Operacoes.Titulos.Carne in 'Controle.Operacoes.Titulos.Carne.pas' {ControleOperacoesTitulosCarne: TUniForm},
  Controle.Operacoes.TituloReceber.Documentos in 'Controle.Operacoes.TituloReceber.Documentos.pas' {ControleOperacoesTituloReceberDocumentos: TUniForm},
  Controle.Consulta.Representante in 'Controle.Consulta.Representante.pas' {ControleConsultaRepresentante: TUniFrame},
  Controle.Cadastro.Representante in 'Controle.Cadastro.Representante.pas' {ControleCadastroRepresentante: TUniForm},
  Controle.Operacoes.TituloPagar.Documentos in 'Controle.Operacoes.TituloPagar.Documentos.pas' {ControleOperacoesTituloPagarDocumentos: TUniForm},
  Controle.Operacoes.CriarTituloPagar in 'Controle.Operacoes.CriarTituloPagar.pas' {ControleOperacoesCriarTituloPagar: TUniForm},
  Controle.Cadastro.TituloPagar in 'Controle.Cadastro.TituloPagar.pas' {ControleCadastroTituloPagar: TUniForm},
  Controle.Consulta.TituloPagar in 'Controle.Consulta.TituloPagar.pas' {ControleConsultaTituloPagar: TUniFrame},
  Controle.Consulta.Caixa in 'Controle.Consulta.Caixa.pas' {ControleConsultaCaixa: TUniFrame},
  Controle.Cadastro.Caixa in 'Controle.Cadastro.Caixa.pas' {ControleCadastroCaixa: TUniForm},
  Controle.Cadastro.Caixa.Operacao in 'Controle.Cadastro.Caixa.Operacao.pas' {ControleCadastroCaixaOperacao: TUniForm},
  Controle.Operacoes.logout in 'Controle.Operacoes.logout.pas' {ControleOperacoesLogout: TUniForm},
  Controle.Operacoes.Caixa in 'Controle.Operacoes.Caixa.pas' {ControleOperacoesCaixa: TUniForm},
  Controle.Cadastro.Cliente in 'Controle.Cadastro.Cliente.pas' {ControleCadastroCliente: TUniForm},
  Controle.Cadastro.Menu.Schema in 'Controle.Cadastro.Menu.Schema.pas' {ControleCadastroMenuSchema: TUniForm},
  Controle.Login in 'Controle.Login.pas' {ControleLogin: TUniLoginForm},
  Controle.Consulta.Usuario in 'Controle.Consulta.Usuario.pas' {ControleConsultaUsuario: TUniFrame},
  Controle.Main.Module in 'Controle.Main.Module.pas' {ControleMainModule: TUniGUIMainModule},
  Controle.Cadastro.Menu in 'Controle.Cadastro.Menu.pas' {ControleCadastroMenu: TUniForm},
  Controle.Consulta.Menu in 'Controle.Consulta.Menu.pas' {ControleConsultaMenu: TUniFrame},
  Controle.Consulta.Produto in 'Controle.Consulta.Produto.pas' {ControleConsultaProduto: TUniFrame},
  Controle.Cadastro.Sugestao in 'Controle.Cadastro.Sugestao.pas' {ControleCadastroSugestao: TUniForm},
  Controle.Consulta.Sugestao in 'Controle.Consulta.Sugestao.pas' {ControleConsultaSugestao: TUniFrame},
  Controle.Cadastro.Produto in 'Controle.Cadastro.Produto.pas' {ControleCadastroProduto: TUniForm},
  Controle.Consulta.GerarDocumento in 'Controle.Consulta.GerarDocumento.pas' {ControleConsultaGerarDocumento: TUniForm},
  Controle.Consulta.Geracao.Documento in 'Controle.Consulta.Geracao.Documento.pas' {ControleConsultaGeracaoDocumento: TUniForm},
  Controle.Consulta.TituloReceber.Opcoes in 'Controle.Consulta.TituloReceber.Opcoes.pas' {ControleConsultaTituloReceberOpcoes: TUniForm},
  Controle.Consulta.TituloPagar.Opcoes in 'Controle.Consulta.TituloPagar.Opcoes.pas' {ControleConsultaTituloPagarOpcoes: TUniForm},
  Controle.Consulta.VideoTutoriais in 'Controle.Consulta.VideoTutoriais.pas' {ControleConsultaVideoTutoriais: TUniFrame},
  Controle.Cadastro.BaixarTituloReceber in 'Controle.Cadastro.BaixarTituloReceber.pas' {ControleCadastroBaixarTituloReceber: TUniForm},
  Controle.Cadastro.Cheque in 'Controle.Cadastro.Cheque.pas' {ControleCadastroCheque: TUniForm},
  Controle.Consulta.Modal.Pessoa.TituloPagar in 'Controle.Consulta.Modal.Pessoa.TituloPagar.pas' {ControleConsultaModalPessoaTituloPagar: TUniForm},
  Controle.Consulta.Modal.Pessoa.TituloReceber in 'Controle.Consulta.Modal.Pessoa.TituloReceber.pas' {ControleConsultaModalPessoaTituloReceber: TUniForm},
  Controle.Consulta.ChequesRecebidos in 'Controle.Consulta.ChequesRecebidos.pas' {ControleConsultaChequesRecebidos: TUniFrame},
  Controle.Consulta.Cheque.Destino in 'Controle.Consulta.Cheque.Destino.pas' {ControleConsultaChequeDestino: TUniFrame},
  Controle.Cadastro.Cheque.Destino in 'Controle.Cadastro.Cheque.Destino.pas' {ControleCadastroChequeDestino: TUniForm},
  Controle.Consulta.TituloCategoria in 'Controle.Consulta.TituloCategoria.pas' {ControleConsultaTituloCategoria: TUniFrame},
  Controle.Cadastro.TituloCategoria in 'Controle.Cadastro.TituloCategoria.pas' {ControleCadastroTituloCategoria: TUniForm},
  Controle.Consulta.Modal.TituloCategoria.Receber in 'Controle.Consulta.Modal.TituloCategoria.Receber.pas' {ControleConsultaModalTituloCategoriaReceber: TUniForm},
  Controle.Consulta.Modal.TituloCategoria.Pagar in 'Controle.Consulta.Modal.TituloCategoria.Pagar.pas' {ControleConsultaModalTituloCategoriaPagar: TUniForm},
  Controle.Consulta.ChequesRecebidos.Baixa in 'Controle.Consulta.ChequesRecebidos.Baixa.pas' {ControleConsultaChequesRecebidosBaixa: TUniForm},
  Controle.Consulta.ChequesDepositados in 'Controle.Consulta.ChequesDepositados.pas' {ControleConsultaChequesDepositados: TUniFrame},
  Controle.Consulta.Modal.ChequeDepositados.Itens in 'Controle.Consulta.Modal.ChequeDepositados.Itens.pas' {ControleConsultaModalChequeDepositadosItens: TUniForm},
  Controle.Operacoes.NegociarTituloReceber in 'Controle.Operacoes.NegociarTituloReceber.pas' {ControleOperacoesNegociarTituloReceber: TUniForm},
  Controle.Cadastro.ProdutoCategoria in 'Controle.Cadastro.ProdutoCategoria.pas' {ControleCadastroProdutoCategoria: TUniForm},
  Controle.Consulta.TreeView.ProdutoCategoria in 'Controle.Consulta.TreeView.ProdutoCategoria.pas' {ControleConsultaTreeViewProdutoCategoria: TUniFrame},
  Controle.Consulta.Modal.TreeView.ProdutoCategoria in 'Controle.Consulta.Modal.TreeView.ProdutoCategoria.pas' {ControleConsultaModalTreeViewProdutoCategorias: TUniForm},
  Controle.Cadastro in 'Controle.Cadastro.pas' {ControleCadastro: TUniForm},
  Controle.Consulta.Modal in 'Controle.Consulta.Modal.pas' {ControleConsultaModal: TUniForm},
  Controle.Consulta in 'Controle.Consulta.pas' {ControleConsulta: TUniFrame},
  Controle.Consulta.TreeView in 'Controle.Consulta.TreeView.pas' {ControleConsultaTreeView: TUniFrame},
  Controle.Funcoes in 'Controle.Funcoes.pas',
  Controle.Impressao in 'Controle.Impressao.pas' {ControleImpressao: TUniForm},
  Controle.Operacoes in 'Controle.Operacoes.pas' {ControleOperacoes: TUniForm},
  Controle.Consulta.Modal.TreeView in 'Controle.Consulta.Modal.TreeView.pas' {ControleConsultaModalTreeView: TUniForm},
  Controle.Consulta.TabelaPreco in 'Controle.Consulta.TabelaPreco.pas' {ControleConsultaTabelaPreco: TUniFrame},
  Controle.Cadastro.TabelaPreco in 'Controle.Cadastro.TabelaPreco.pas' {ControleCadastroTabelaPreco: TUniForm},
  Controle.Consulta.Produto.TabelaPrecoExcecao in 'Controle.Consulta.Produto.TabelaPrecoExcecao.pas' {ControleConsultaProdutoTabelaPrecoExcecao: TUniFrame},
  Controle.Cadastro.ProdutoTabelaPrecoExcecao in 'Controle.Cadastro.ProdutoTabelaPrecoExcecao.pas' {ControleCadastroProdutoTabelaPrecoExececao: TUniForm},
  Controle.Consulta.Modal.Produto in 'Controle.Consulta.Modal.Produto.pas' {ControleConsultaModalProduto: TUniForm},
  Controle.Consulta.ProdutoEmbalagem in 'Controle.Consulta.ProdutoEmbalagem.pas' {ControleConsultaProdutoEmbalagem: TUniFrame},
  Controle.Cadastro.ProdutoEmbalagem in 'Controle.Cadastro.ProdutoEmbalagem.pas' {ControleCadastroProdutoEmbalagem: TUniForm},
  Controle.Consulta.GrupoTributario in 'Controle.Consulta.GrupoTributario.pas' {ControleConsultaGrupoTributario: TUniFrame},
  Controle.Cadastro.GrupoTributario in 'Controle.Cadastro.GrupoTributario.pas' {ControleCadastroGrupoTributario: TUniForm},
  Controle.Cadastro.GrupoTributario.Estados in 'Controle.Cadastro.GrupoTributario.Estados.pas' {ControleCadastroGrupoTributarioEstados: TUniForm},
  Controle.Relatorio in 'Controle.Relatorio.pas' {ControleRelatorio: TUniFrame},
  Controle.Relatorio.Cadastro in 'Controle.Relatorio.Cadastro.pas' {ControleRelatorioCadastro: TUniFrame},
  Controle.Relatorio.Cadastro.ContasReceber in 'Controle.Relatorio.Cadastro.ContasReceber.pas' {ControleRelatorioCadastroContasReceber: TUniFrame},
  Controle.Consulta.IntegracaoContasPagar in 'Controle.Consulta.IntegracaoContasPagar.pas' {ControleConsultaIntegracaoContasPagar: TUniFrame},
  Controle.Consulta.Integracao.ContasReceber in 'Controle.Consulta.Integracao.ContasReceber.pas' {ControleConsultaIntegracaoContasReceber: TUniFrame},
  Controle.Relatorio.Cadastro.ContasPagar in 'Controle.Relatorio.Cadastro.ContasPagar.pas' {ControleRelatorioCadastroContasPagar: TUniFrame},
  Controle.Consulta.Integracao.ContasRecebidas in 'Controle.Consulta.Integracao.ContasRecebidas.pas' {ControleConsultaIntegracaoConstasRecebidas: TUniFrame},
  Controle.Operacoes.Integracao.CalculoJuros in 'Controle.Operacoes.Integracao.CalculoJuros.pas' {ControleOperacoesIntegracaoCalculoJuros: TUniForm},
  Controle.Operacoes.Integracao.NegociarTituloReceber in 'Controle.Operacoes.Integracao.NegociarTituloReceber.pas' {ControleOperacoesIntegracaoNegociarTituloReceber: TUniForm},
  Controle.Operacoes.ConferenciaAssinatura in 'Controle.Operacoes.ConferenciaAssinatura.pas' {ControleOperacoesConferenciaAssinatura: TUniForm},
  Controle.Cadastro.BaixartituloPagar in 'Controle.Cadastro.BaixartituloPagar.pas' {ControleCadastroBaixartituloPagar: TUniForm},
  Controle.Operacoes.MensagensCobranca in 'Controle.Operacoes.MensagensCobranca.pas' {ControleOperacoesMensagensCobranca: TUniForm},
  Funcoes.client in 'Funcoes.client.pas',
  Envia.Recebe.Dados.Json in 'Envia.Recebe.Dados.Json.pas' {EnviaRecebeDadosJson},
  Controle.Envia.Mensagem in 'Controle.Envia.Mensagem.pas' {ControleEnviaMensagem: TUniForm},
  Controle.Consulta.DescontosVales in 'Controle.Consulta.DescontosVales.pas' {ControleConsultaDescontosVales: TUniFrame},
  Controle.Cadastro.DescontosVales in 'Controle.Cadastro.DescontosVales.pas' {ControleCadastroDescontosVales: TUniForm},
  Controle.Envia.Mensagem.Confirma in 'Controle.Envia.Mensagem.Confirma.pas' {ControleEnviaMensagemConfirma: TUniForm},
  Client.Aguarde in 'Client.Aguarde.pas' {ClientAguarde: TUniForm},
  Controle.Relatorio.Cadastro.FluxoCaixa in 'Controle.Relatorio.Cadastro.FluxoCaixa.pas' {ControleRelatorioCadastroFluxoCaixa: TUniFrame},
  Controle.Consulta.Integracao.BergCheques in 'Controle.Consulta.Integracao.BergCheques.pas' {ControleConsultaIntegracaoBergCheques: TUniFrame},
  Controle.Consulta.DocumentosFiscais.NFe in 'Controle.Consulta.DocumentosFiscais.NFe.pas' {ControleConsultaDocumentosFiscaisNFe: TUniFrame},
  Controle.Cadastro.DocumentosFiscais.NFe in 'Controle.Cadastro.DocumentosFiscais.NFe.pas' {ControleCadastroDocumentosFiscaisNFe: TUniForm},
  Controle.Cadastro.DocumentosFiscais.NFe.Produto in 'Controle.Cadastro.DocumentosFiscais.NFe.Produto.pas' {ControleCadastroDocumentosFiscaisNFeProduto: TUniForm};

{$R *.res}

{$ifndef UNIGUI_VCL}
exports
  GetExtensionVersion,
  HttpExtensionProc,
  TerminateExtension;
{$endif}

begin
{$ifdef UNIGUI_VCL}
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TControleServerModule.Create(Application);
  Application.Run;
{$endif}
end.

